### Variables 
@apiurl = http://localhost:3000/api
@tableName = pessoafisica

GET {{apiurl}}/{{tableName}} HTTP/1.1

###
GET {{apiurl}}/{{tableName}}/1

###
POST {{apiurl}}/{{tableName}}
Content-Type: application/json; charset=utf-8

{
    "nome": "teste",
    "email": "rafael@teste2.com",
    "senha": 12345
}

###
DELETE {{apiurl}}/{{tableName}}/1

###
PUT {{apiurl}}/{{tableName}}/1
Content-Type: application/json; charset=utf-8

{
    "nome": "RR Tutu",
    "email": "rafael@teste.com",
    "senha": 12345
}